node /home/vrm/forestadmin_csv/getITC
node /home/vrm/forestadmin_csv/getITCenhanced
node /home/vrm/forestadmin_csv/uploadBruno
node /home/vrm/forestadmin_csv/uploadBruno4
node /home/vrm/forestadmin_csv/uploadBruno6
node /home/vrm/forestadmin_csv/uploadITC-ID
node /home/vrm/forestadmin_csv/uploadJesus
node /home/vrm/forestadmin_csv/uploadOyon
node /home/vrm/forestadmin_csv/uploadSam2
node /home/vrm/forestadmin_csv/uploadSam3
node /home/vrm/forestadmin_csv/uploadSam4
node /home/vrm/forestadmin_csv/uploadSkyler